# Site Configuration

title: My Blog
description: A personal blog built with Giggle
author: Your Name

# Site settings
site:
  title: My Blog
  description: A personal blog built with Giggle
  author: Your Name
  url: http://localhost:8000

# Features
features:
  blog_pages: true
  tag_pages: true

# Directory paths
paths:
  blogs: sample_markdowns/blog
  pages: sample_markdowns/pages
  assets: assets

# Navigation
nav:
  - name: Home
    url: /
  - name: Blog
    url: /blog
  - name: Tags
    url: /tags

# Social media links
social_links:
  github: https://github.com/yourusername
  twitter: https://twitter.com/yourusername

# Typography settings
typography:
  font_family:
    body: "'Inter', system-ui, -apple-system, sans-serif"
    headers: "'Inter', system-ui, -apple-system, sans-serif"
  sizes:
    body: "16px"
    headers:
      h1: "2.5rem"
      h2: "2rem"
      h3: "1.75rem"
      h4: "1.5rem"
      h5: "1.25rem"
      h6: "1rem"
  line_height:
    body: "1.6"
    headers: "1.3"

# Colors
colors:
  primary: "#3b82f6"
  background: "#ffffff"
  background_secondary: "#f8f9fa"
  text: "#1a1a1a"
  text_secondary: "#4a5568"
  accent: "#60a5fa"
  border: "#e5e7eb"
  card_shadow: "rgba(0, 0, 0, 0.1)"

# Component styling
style:
  tag:
    color: "#666666"
    bg_color: "#f5f5f5"
    border: "1px solid #dddddd"
    border_radius: "3px"
    padding: "2px 8px"
    font_size: "0.8em"
    mb: 1
    ml: 0
    mr: 1
    mt: 0
    display: "inline-block"
  blog_card:
    bg_color: "#ffffff"
    border: "1px solid #e5e7eb"
    border_radius: "8px"
    padding: "1.5rem"
    margin_bottom: "1.5rem"
    box_shadow: "0 2px 4px rgba(0, 0, 0, 0.05)"
    transition: "transform 0.2s, box-shadow 0.2s"
    hover:
      transform: "translateY(-2px)"
      box_shadow: "0 4px 6px rgba(0, 0, 0, 0.1)"
  blog_title:
    color: "#1a1a1a"
    font_size: "1.5rem"
    font_weight: "600"
    margin_bottom: "0.5rem"
    line_height: "1.3"
  blog_meta:
    color: "#4a5568"
    font_size: "0.875rem"
    margin_bottom: "1rem"
  blog_excerpt:
    color: "#4a5568"
    font_size: "1rem"
    line_height: "1.6"
    margin_bottom: "1rem"
  blog_link:
    color: "#3b82f6"
    text_decoration: "none"
    font_weight: "500"
    hover:
      color: "#60a5fa"
  navbar:
    color: black
    bg_color: "#ffffff"
    border_bottom: "1px solid #e5e7eb"
    padding: "1rem 0"
  footer:
    color: "#4a5568"
    bg_color: "#f8f9fa"
    border_top: "1px solid #e5e7eb"
    padding: "2rem 0"
